version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-dev-v
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: sh -c "pnpm prisma migrate dev && pnpm run start:dev"
    volumes:
      - .:/app
      - /app/node_modules


volumes:
  postgres-data:
